repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: uv run --locked mypy src/lb_mapper/ tests/ --strict
        language: system
        files: ^(src/lb_mapper|tests)/.*\.pyi?$
        pass_filenames: false

      - id: ruff-check
        name: ruff check
        entry: uv run --locked ruff check --fix
        language: system
        types_or: [python, pyi]

      - id: ruff-format
        name: ruff format
        entry: uv run --locked ruff format
        language: system
        types_or: [python, pyi]

      - id: bandit
        name: bandit
        entry: uv run --locked bandit -r src/lb_mapper/
        language: system
        files: ^src/lb_mapper/.*\.py$
        pass_filenames: false
